/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineSysMng;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author romi
 */
public class Lab_Assistant extends javax.swing.JFrame {

    /**
     * Creates new form Lab_Assistant
     */
    public Lab_Assistant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtPhoneNo = new javax.swing.JTextField();
        jtxtLabAssId = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtLabNo = new javax.swing.JTextField();
        jbtnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtnbck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Chiller", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAB_ASSISTANT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 70, 620, 110);

        jLabel3.setFont(new java.awt.Font("Chiller", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText(" Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 350, 170, 50);

        jLabel4.setFont(new java.awt.Font("Chiller", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Lab_Assistant Id");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 260, 230, 50);

        jLabel6.setFont(new java.awt.Font("Chiller", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Lab_No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 440, 230, 50);

        jLabel7.setFont(new java.awt.Font("Chiller", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Phone_No");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 530, 230, 50);

        jtxtPhoneNo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtPhoneNo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtPhoneNo.setText("Enter Lab_Assistant Phone No. here...");
        jtxtPhoneNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtPhoneNoMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtPhoneNo);
        jtxtPhoneNo.setBounds(280, 530, 360, 40);

        jtxtLabAssId.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtLabAssId.setForeground(new java.awt.Color(153, 153, 153));
        jtxtLabAssId.setText("Enter Lad_Assistant Id here...");
        jtxtLabAssId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLabAssIdMouseClicked(evt);
            }
        });
        jtxtLabAssId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLabAssIdActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtLabAssId);
        jtxtLabAssId.setBounds(280, 260, 360, 40);

        jtxtName.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtName.setForeground(new java.awt.Color(153, 153, 153));
        jtxtName.setText("Enter Lab_Assistant Name here...");
        jtxtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNameMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtName);
        jtxtName.setBounds(280, 350, 360, 40);

        jtxtLabNo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtLabNo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtLabNo.setText("Enter Lab_No here...");
        jtxtLabNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLabNoMouseClicked(evt);
            }
        });
        jtxtLabNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLabNoActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtLabNo);
        jtxtLabNo.setBounds(280, 440, 360, 40);

        jbtnSave.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jbtnSave.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSave.setText("SAVE");
        jbtnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jbtnSave.setContentAreaFilled(false);
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSave);
        jbtnSave.setBounds(260, 630, 120, 40);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 30, 640, 770);

        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 50, 640, 770);

        jbtnbck.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnbck.setForeground(new java.awt.Color(255, 255, 255));
        jbtnbck.setText("BACK");
        jbtnbck.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jbtnbck.setContentAreaFilled(false);
        jbtnbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbckActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbck);
        jbtnbck.setBounds(1330, 730, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/cbcc21d0d7ae0b6d494f3ea1647c429e.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1630, 870);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1601, 913));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbckActionPerformed
        systemExit();
        this.hide();
        MainPage1 mp1=new MainPage1();
        mp1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnbckActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        try {
                 Connection con=getConnection();
                PreparedStatement ps=con.prepareStatement("INSERT INTO Lab_Assistant(Lab_Assistant_Id,Name,Lab_No,Phone_No)"+"values(?,?,?,?)");
                ps.setString(1,jtxtLabAssId.getText());
                ps.setString(2,jtxtName.getText());
                ps.setString(3,jtxtLabNo.getText());
                ps.setString(4,jtxtPhoneNo.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Inserted");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jtxtLabNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLabNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLabNoActionPerformed

    private void jtxtLabAssIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLabAssIdMouseClicked
        jtxtLabAssId.setText(null);
    }//GEN-LAST:event_jtxtLabAssIdMouseClicked

    private void jtxtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNameMouseClicked
        jtxtName.setText(null);
    }//GEN-LAST:event_jtxtNameMouseClicked

    private void jtxtLabNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLabNoMouseClicked
       jtxtLabNo.setText(null);
    }//GEN-LAST:event_jtxtLabNoMouseClicked

    private void jtxtPhoneNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtPhoneNoMouseClicked
        jtxtPhoneNo.setText(null);
    }//GEN-LAST:event_jtxtPhoneNoMouseClicked

    private void jtxtLabAssIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLabAssIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLabAssIdActionPerformed

     public Connection getConnection()
    {
        
        Connection con=null;
        try { 
            con=DriverManager.getConnection("jdbc:mysql://localhost/system_mgmnt","root","");
            JOptionPane.showMessageDialog(null,"Connected");
            return con;
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Not Connected");
            return null;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab_Assistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab_Assistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab_Assistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab_Assistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab_Assistant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnbck;
    private javax.swing.JTextField jtxtLabAssId;
    private javax.swing.JTextField jtxtLabNo;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhoneNo;
    // End of variables declaration//GEN-END:variables
private void systemExit()
    {
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}
