/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineSysMng;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import OnlineSysMng.MainPage1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author romi
 */
public class Login1 extends javax.swing.JFrame {

    public static String Password;
    public static String Username;
    public static String Answer;
    /**
     * Creates new form OnlineSysMng
     */
    public Login1() {
        /*this.setAlwaysOnTop(true);
        *///this.setResizable(true);
        //this.setVisible(true);
        initComponents();
        /*Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getWidth();
        this.setSize(xsize,ysize);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtUserName1 = new javax.swing.JTextField();
        jbtnLogin1 = new javax.swing.JButton();
        jPassword1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        SetPswrd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jbtnSave = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtAnswer = new javax.swing.JTextField();
        jbtnLogin2 = new javax.swing.JButton();
        jtxtPassword = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtxtUserName3 = new javax.swing.JTextField();
        jtxtPassword1 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(155, 865));

        jPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/images.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 80, 230, 230);

        jButton1.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("FORGOT PASSWORD");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 490, 230, 50);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGISTER");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(0, 580, 230, 50);

        jButton3.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LOGIN");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(0, 400, 230, 50);

        jLabel6.setBackground(new java.awt.Color(6, 34, 62));
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 310, 230, 480);

        jPanel3.setLayout(new java.awt.CardLayout());

        Login.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADMINISTRATOR LOGIN");
        Login.add(jLabel8);
        jLabel8.setBounds(150, 140, 470, 80);

        jLabel9.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASSWORD");
        Login.add(jLabel9);
        jLabel9.setBounds(90, 350, 160, 40);

        jLabel10.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("USERNAME");
        Login.add(jLabel10);
        jLabel10.setBounds(90, 260, 160, 40);

        jtxtUserName1.setFont(new java.awt.Font("Californian FB", 2, 18)); // NOI18N
        jtxtUserName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtUserName1MouseClicked(evt);
            }
        });
        jtxtUserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserName1ActionPerformed(evt);
            }
        });
        Login.add(jtxtUserName1);
        jtxtUserName1.setBounds(240, 260, 370, 40);

        jbtnLogin1.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnLogin1.setForeground(new java.awt.Color(153, 255, 255));
        jbtnLogin1.setText("LOGIN");
        jbtnLogin1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jbtnLogin1.setContentAreaFilled(false);
        jbtnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogin1ActionPerformed(evt);
            }
        });
        Login.add(jbtnLogin1);
        jbtnLogin1.setBounds(240, 430, 130, 40);

        jPassword1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPassword1MouseClicked(evt);
            }
        });
        Login.add(jPassword1);
        jPassword1.setBounds(240, 350, 370, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/secure.jpg"))); // NOI18N
        Login.add(jLabel11);
        jLabel11.setBounds(-240, 0, 1720, 870);

        jPanel3.add(Login, "card2");

        SetPswrd.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SET NEW PASSWORD");
        SetPswrd.add(jLabel2);
        jLabel2.setBounds(90, 140, 530, 80);

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NEW PASSWORD");
        SetPswrd.add(jLabel3);
        jLabel3.setBounds(40, 450, 210, 40);

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME");
        SetPswrd.add(jLabel4);
        jLabel4.setBounds(90, 260, 160, 40);

        jLabel20.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("SECURITY");
        SetPswrd.add(jLabel20);
        jLabel20.setBounds(110, 340, 120, 40);

        jLabel21.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("QUESTION");
        SetPswrd.add(jLabel21);
        jLabel21.setBounds(100, 360, 120, 40);

        jtxtUserName.setFont(new java.awt.Font("Californian FB", 2, 18)); // NOI18N
        SetPswrd.add(jtxtUserName);
        jtxtUserName.setBounds(240, 260, 370, 40);

        jTextField1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        SetPswrd.add(jTextField1);
        jTextField1.setBounds(240, 380, 370, 40);

        jbtnSave.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnSave.setForeground(new java.awt.Color(153, 255, 255));
        jbtnSave.setText("SAVE");
        jbtnSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jbtnSave.setContentAreaFilled(false);
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        SetPswrd.add(jbtnSave);
        jbtnSave.setBounds(240, 530, 130, 40);

        jPassword.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        SetPswrd.add(jPassword);
        jPassword.setBounds(240, 450, 370, 40);

        jComboBox2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What was your birth place?", "What is your favourite colour?", "Who is your best friend?", " ", " " }));
        SetPswrd.add(jComboBox2);
        jComboBox2.setBounds(240, 320, 370, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/secure.jpg"))); // NOI18N
        SetPswrd.add(jLabel1);
        jLabel1.setBounds(-170, 0, 1620, 870);

        jPanel3.add(SetPswrd, "card3");

        Register.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Californian FB", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("REGISTER");
        Register.add(jLabel12);
        jLabel12.setBounds(70, 100, 470, 80);

        jLabel13.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("QUESTION");
        Register.add(jLabel13);
        jLabel13.setBounds(90, 360, 120, 40);

        jLabel14.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("USERNAME");
        Register.add(jLabel14);
        jLabel14.setBounds(90, 220, 160, 40);

        jtxtAnswer.setFont(new java.awt.Font("Californian FB", 2, 18)); // NOI18N
        Register.add(jtxtAnswer);
        jtxtAnswer.setBounds(240, 420, 370, 40);

        jbtnLogin2.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnLogin2.setForeground(new java.awt.Color(153, 255, 255));
        jbtnLogin2.setText("Register");
        jbtnLogin2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jbtnLogin2.setContentAreaFilled(false);
        jbtnLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogin2ActionPerformed(evt);
            }
        });
        Register.add(jbtnLogin2);
        jbtnLogin2.setBounds(240, 570, 130, 40);

        jtxtPassword.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });
        Register.add(jtxtPassword);
        jtxtPassword.setBounds(240, 280, 370, 40);

        jComboBox1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What was your birth place?", "What is your favourite colour?", "Who is your best friend?", " ", " " }));
        Register.add(jComboBox1);
        jComboBox1.setBounds(240, 350, 370, 40);

        jtxtUserName3.setFont(new java.awt.Font("Californian FB", 2, 18)); // NOI18N
        Register.add(jtxtUserName3);
        jtxtUserName3.setBounds(240, 220, 370, 40);

        jtxtPassword1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        Register.add(jtxtPassword1);
        jtxtPassword1.setBounds(240, 490, 370, 40);

        jLabel16.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ANSWER");
        Register.add(jLabel16);
        jLabel16.setBounds(110, 430, 100, 40);

        jLabel17.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SECURITY");
        Register.add(jLabel17);
        jLabel17.setBounds(100, 340, 120, 40);

        jLabel18.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("OLD PASSWORD");
        Register.add(jLabel18);
        jLabel18.setBounds(40, 280, 210, 40);

        jLabel19.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("SET PASSWORD");
        Register.add(jLabel19);
        jLabel19.setBounds(40, 490, 200, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/secure.jpg"))); // NOI18N
        Register.add(jLabel15);
        jLabel15.setBounds(-170, 0, 1620, 870);

        jPanel3.add(Register, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1320, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 232, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1569, 912));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jPanel3.removeAll();
        jPanel3.add(SetPswrd);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtUserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserName1ActionPerformed

    private void jbtnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogin1ActionPerformed
        try {
                Connection con=getConnection();
                PreparedStatement ps=con.prepareStatement("SELECT Username,Password FROM LOGIN WHERE Username=? AND Password=?");
                ps.setString(1,jtxtUserName1.getText());
                ps.setString(2,String.valueOf(jPassword1.getText()));
                ResultSet result=ps.executeQuery();
                if(result.next())
                {
                    JOptionPane.showMessageDialog(null,"Login Successful");
                    setVisible(false);
                    systemExit();
                    this.hide();
                    MainPage1 mp=new MainPage1();
                    mp.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Username or Password","Login Failed",JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
                JOptionPane.showMessageDialog(null,"Invalid Username or Password","Login Failed",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jbtnLogin1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jPanel3.removeAll();
        jPanel3.add(Login);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel3.removeAll();
        jPanel3.add(Register);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogin2ActionPerformed
        try {
                 Connection con=getConnection();
                PreparedStatement ps=con.prepareStatement("SELECT * FROM LOGIN WHERE Password = ?");
                ps.setString(1,String.valueOf(jtxtPassword.getText()));
                ResultSet result=ps.executeQuery();
                if(result.next())
                {
                ps=con.prepareStatement("UPDATE Login SET Username=?, Answer=?, Password=?");
                ps.setString(1,jtxtUserName3.getText());
                ps.setString(2,jtxtAnswer.getText());
                ps.setString(3,String.valueOf(jtxtPassword1.getText()));
                //ps.setString(4,String.valueOf(jtxtPassword.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Registered");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid Old Password","Registration Denied",JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
                JOptionPane.showMessageDialog(null,"Invalid Old Password","Registration Denied",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jbtnLogin2ActionPerformed

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        try {
            Connection con=getConnection();
            PreparedStatement ps=con.prepareStatement("SELECT * FROM Login WHERE Username=? AND Answer=?");
            ps.setString(1,jtxtUserName.getText());
            ps.setString(2,String.valueOf(jTextField1.getText()));
            ResultSet result=ps.executeQuery();
                if(result.next())
                {
                    ps=con.prepareStatement("UPDATE Login SET Password=? WHERE Username=? AND Answer=?");
                    ps.setString(1,String.valueOf(jPassword.getText()));
                    ps.setString(2,jtxtUserName.getText());
                    ps.setString(3,String.valueOf(jTextField1.getText()));
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Updation Successful");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Updation Unsuccessful","Login Failed",JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
            Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Updation Unsuccessful!!!");
        }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jPassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassword1MouseClicked
jPassword1.setText(null);       
    }//GEN-LAST:event_jPassword1MouseClicked

    private void jtxtUserName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtUserName1MouseClicked
       jtxtUserName1.setText(null);
    }//GEN-LAST:event_jtxtUserName1MouseClicked

     public Connection getConnection()
    {
        Connection con=null;
        try { 
            con=DriverManager.getConnection("jdbc:mysql://localhost/system_mgmnt","root","");
            //JOptionPane.showMessageDialog(null,"Connected");
            return con;
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Not Connected to Database");
            return null;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private javax.swing.JPanel SetPswrd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnLogin1;
    private javax.swing.JButton jbtnLogin2;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JTextField jtxtAnswer;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JPasswordField jtxtPassword1;
    private javax.swing.JTextField jtxtUserName;
    private javax.swing.JTextField jtxtUserName1;
    private javax.swing.JTextField jtxtUserName3;
    // End of variables declaration//GEN-END:variables
private void systemExit()
    {
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}
