/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineSysMng;
import OnlineSysMng.Login1;
import java.awt.event.WindowEvent;
import OnlineSysMng.New_lab1;
import OnlineSysMng.Lab_Assistant;
import OnlineSysMng.Not_Working;
import OnlineSysMng.Orders;
import OnlineSysMng.Update;
import OnlineSysMng.Delete1;
import com.sun.istack.internal.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
/**
 *
 * @author romi
 */
public class MainPage1 extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnNewLab = new javax.swing.JButton();
        jbtnLabAssistnt = new javax.swing.JButton();
        jbtnNotWrkng = new javax.swing.JButton();
        jbtnOrder = new javax.swing.JButton();
        jbtnSupplier = new javax.swing.JButton();
        jbtnbck = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jbtnNewLab.setBackground(new java.awt.Color(153, 204, 255));
        jbtnNewLab.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jbtnNewLab.setForeground(new java.awt.Color(255, 0, 0));
        jbtnNewLab.setText("NEW_LAB");
        jbtnNewLab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jbtnNewLab.setContentAreaFilled(false);
        jbtnNewLab.setSelected(true);
        jbtnNewLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewLabActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNewLab);
        jbtnNewLab.setBounds(620, 210, 260, 50);

        jbtnLabAssistnt.setBackground(new java.awt.Color(153, 204, 255));
        jbtnLabAssistnt.setFont(new java.awt.Font("Chiller", 0, 36)); // NOI18N
        jbtnLabAssistnt.setForeground(new java.awt.Color(255, 0, 51));
        jbtnLabAssistnt.setText("LAB_ASSISTENT");
        jbtnLabAssistnt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jbtnLabAssistnt.setContentAreaFilled(false);
        jbtnLabAssistnt.setSelected(true);
        jbtnLabAssistnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLabAssistntActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLabAssistnt);
        jbtnLabAssistnt.setBounds(620, 300, 260, 50);

        jbtnNotWrkng.setBackground(new java.awt.Color(153, 204, 255));
        jbtnNotWrkng.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jbtnNotWrkng.setForeground(new java.awt.Color(255, 0, 0));
        jbtnNotWrkng.setText("NOT_WORKING SYSTEMS...");
        jbtnNotWrkng.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jbtnNotWrkng.setContentAreaFilled(false);
        jbtnNotWrkng.setSelected(true);
        jbtnNotWrkng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNotWrkngActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNotWrkng);
        jbtnNotWrkng.setBounds(560, 380, 380, 50);

        jbtnOrder.setBackground(new java.awt.Color(153, 204, 255));
        jbtnOrder.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jbtnOrder.setForeground(new java.awt.Color(255, 0, 0));
        jbtnOrder.setText("ORDER");
        jbtnOrder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jbtnOrder.setContentAreaFilled(false);
        jbtnOrder.setSelected(true);
        jbtnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrderActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnOrder);
        jbtnOrder.setBounds(620, 470, 260, 50);

        jbtnSupplier.setBackground(new java.awt.Color(153, 204, 255));
        jbtnSupplier.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jbtnSupplier.setForeground(new java.awt.Color(255, 0, 0));
        jbtnSupplier.setText("SUPPLIER");
        jbtnSupplier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jbtnSupplier.setContentAreaFilled(false);
        jbtnSupplier.setSelected(true);
        jbtnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSupplier);
        jbtnSupplier.setBounds(620, 550, 260, 50);

        jbtnbck.setBackground(new java.awt.Color(255, 255, 153));
        jbtnbck.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnbck.setText("LOG OUT");
        jbtnbck.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jbtnbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbckActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbck);
        jbtnbck.setBounds(30, 790, 140, 50);

        jbtnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        jbtnUpdate.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jbtnUpdate.setForeground(new java.awt.Color(255, 0, 51));
        jbtnUpdate.setText("UPDATE");
        jbtnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        jbtnUpdate.setIconTextGap(2);
        jbtnUpdate.setSelected(true);
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate);
        jbtnUpdate.setBounds(430, 660, 240, 60);

        jbtnDelete.setBackground(new java.awt.Color(255, 255, 255));
        jbtnDelete.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(255, 0, 51));
        jbtnDelete.setText("DELETE");
        jbtnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 2, true));
        jbtnDelete.setIconTextGap(2);
        jbtnDelete.setSelected(true);
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete);
        jbtnDelete.setBounds(840, 660, 240, 60);

        jLabel3.setFont(new java.awt.Font("Chiller", 0, 125)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("S");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 20, 50, 120);

        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 150, 810, 620);

        jLabel2.setFont(new java.awt.Font("Chiller", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("YSTEM LABORATORY MANAGEMENT...");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 20, 860, 130);

        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 102), 3, true));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 140, 830, 640);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/dna_nano_tech-wide.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1570, 870);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1573, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1591, 920));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbckActionPerformed
       systemExit();
       this.hide();
       Login1 lg1=new Login1();
       lg1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnbckActionPerformed

    private void jbtnNewLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewLabActionPerformed
        systemExit();
        this.hide();
        New_lab1 nw1=new New_lab1();
        nw1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnNewLabActionPerformed

    private void jbtnLabAssistntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLabAssistntActionPerformed
       systemExit();
       this.hide();
       Lab_Assistant la=new Lab_Assistant();
       la.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLabAssistntActionPerformed

    private void jbtnNotWrkngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNotWrkngActionPerformed
       systemExit();
       this.hide();
       Not_Working nw=new Not_Working();
       nw.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnNotWrkngActionPerformed

    private void jbtnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrderActionPerformed
       systemExit();
       this.hide();
       Orders o=new Orders();
       o.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnOrderActionPerformed

    private void jbtnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSupplierActionPerformed
       systemExit();
       this.hide();
       Supplier s=new Supplier();
       s.setVisible(true);          
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnSupplierActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        systemExit();
        this.hide();
        Delete1 del=new Delete1();
        del.setVisible(true);
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        systemExit();
        this.hide();
        Update up=new Update();
        up.setVisible(true);
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnLabAssistnt;
    private javax.swing.JButton jbtnNewLab;
    private javax.swing.JButton jbtnNotWrkng;
    private javax.swing.JButton jbtnOrder;
    private javax.swing.JButton jbtnSupplier;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JButton jbtnbck;
    // End of variables declaration//GEN-END:variables
private void systemExit()
    {
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}
