/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineSysMng;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author romi
 */
public class New_lab1 extends javax.swing.JFrame {

    /**
     * Creates new form New_lab
     */
    public New_lab1() {
        initComponents();
        getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtLabNo = new javax.swing.JTextField();
        jtxtLabName = new javax.swing.JTextField();
        jtxtDept = new javax.swing.JTextField();
        jtxtNoSys = new javax.swing.JTextField();
        jtxtBuildingName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtSubmit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnbck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jtxtLabNo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtLabNo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtLabNo.setText("Enter Lab No here...");
        jtxtLabNo.setBorder(null);
        jtxtLabNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLabNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxtLabNoMouseEntered(evt);
            }
        });
        jtxtLabNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLabNoActionPerformed(evt);
            }
        });
        jtxtLabNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtLabNoKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtLabNo);
        jtxtLabNo.setBounds(280, 100, 370, 50);

        jtxtLabName.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtLabName.setForeground(new java.awt.Color(153, 153, 153));
        jtxtLabName.setText("Enter Lab Name here...");
        jtxtLabName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLabNameMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtLabName);
        jtxtLabName.setBounds(280, 180, 370, 50);

        jtxtDept.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtDept.setForeground(new java.awt.Color(153, 153, 153));
        jtxtDept.setText("Enter Department here...");
        jtxtDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDeptMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtDept);
        jtxtDept.setBounds(280, 260, 370, 50);

        jtxtNoSys.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtNoSys.setForeground(new java.awt.Color(153, 153, 153));
        jtxtNoSys.setText("Enter No. of Systems here...");
        jtxtNoSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNoSysMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtNoSys);
        jtxtNoSys.setBounds(280, 340, 370, 50);

        jtxtBuildingName.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtBuildingName.setForeground(new java.awt.Color(153, 153, 153));
        jtxtBuildingName.setText("Enter Building Name here...");
        jtxtBuildingName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBuildingNameMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtBuildingName);
        jtxtBuildingName.setBounds(280, 420, 370, 50);

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Chiller", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAB_NO");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 100, 190, 50);

        jLabel3.setFont(new java.awt.Font("Chiller", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LAB_NAME");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 180, 190, 50);

        jLabel4.setFont(new java.awt.Font("Chiller", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DEPARTMENT");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 260, 190, 50);

        jLabel5.setFont(new java.awt.Font("Chiller", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NO_OF_SYSTEMS");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 340, 190, 50);

        jLabel6.setFont(new java.awt.Font("Chiller", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BUILDING_NAME");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(89, 420, 174, 50);

        jtxtSubmit.setBackground(new java.awt.Color(0, 0, 0));
        jtxtSubmit.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jtxtSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jtxtSubmit.setText("SUBMIT");
        jtxtSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jtxtSubmit.setContentAreaFilled(false);
        jtxtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtSubmit);
        jtxtSubmit.setBounds(80, 560, 140, 40);

        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 70, 620, 440);

        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 50, 660, 790);

        jbtnbck.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnbck.setForeground(new java.awt.Color(255, 255, 255));
        jbtnbck.setText("BACK");
        jbtnbck.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jbtnbck.setContentAreaFilled(false);
        jbtnbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbckActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbck);
        jbtnbck.setBounds(1360, 780, 170, 50);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/download.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1610, 880);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1588, 919));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtLabNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLabNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLabNoActionPerformed

    private void jbtnbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbckActionPerformed
        systemExit();
        this.hide();
        MainPage1 mp1=new MainPage1();
        mp1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnbckActionPerformed

    private void jtxtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubmitActionPerformed
        if(checkInputs())
        {
            try {
                 Connection con=getConnection();
                PreparedStatement ps=con.prepareStatement("INSERT INTO New_lab1(LAB_NO,LAB_NAME,DEPARTMENT,NO_OF_SYSTEMS,BUILDING_NAME)"+"values(?,?,?,?,?)");
                ps.setString(1,jtxtLabNo.getText());
                ps.setString(2,jtxtLabName.getText());
                ps.setString(3,jtxtDept.getText());
                ps.setString(4,jtxtNoSys.getText());
                ps.setString(5,jtxtBuildingName.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Inserted");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null,"One or more field are empty");
        }
    }//GEN-LAST:event_jtxtSubmitActionPerformed

    private void jtxtLabNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLabNoMouseClicked
       jtxtLabNo.setText(null);
    }//GEN-LAST:event_jtxtLabNoMouseClicked

    private void jtxtLabNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLabNameMouseClicked
        jtxtLabName.setText(null);
    }//GEN-LAST:event_jtxtLabNameMouseClicked

    private void jtxtDeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDeptMouseClicked
        jtxtDept.setText(null);
    }//GEN-LAST:event_jtxtDeptMouseClicked

    private void jtxtNoSysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNoSysMouseClicked
        jtxtNoSys.setText(null);
    }//GEN-LAST:event_jtxtNoSysMouseClicked

    private void jtxtBuildingNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBuildingNameMouseClicked
       jtxtBuildingName.setText(null);
    }//GEN-LAST:event_jtxtBuildingNameMouseClicked

    private void jtxtLabNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLabNoMouseEntered
       
    }//GEN-LAST:event_jtxtLabNoMouseEntered

    private void jtxtLabNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtLabNoKeyTyped
       
    }//GEN-LAST:event_jtxtLabNoKeyTyped

    public Connection getConnection()
    {
        
        Connection con=null;
        try { 
            con=DriverManager.getConnection("jdbc:mysql://localhost/system_mgmnt","root","");
            JOptionPane.showMessageDialog(null,"Connected");
            return con;
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Not Connected");
            return null;
        }
        
    }
    
    public boolean checkInputs()
    {
        if(jtxtLabNo.getText()==null
                || jtxtLabName.getText()==null
                || jtxtDept.getText()==null
                || jtxtNoSys.getText()==null
                || jtxtBuildingName.getText()==null)
        {
            return false;
        }
        else{
            try{
                /*jtxtLabNo.getText();
                jtxtLabName.getText();
                jtxtDept.getText();
                jtxtNoSys.getText();
                jtxtBuildingName.getText();*/
                return true;
            }catch(Exception ex){
                return false;
            }
        }
                }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_lab1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_lab1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnbck;
    private javax.swing.JTextField jtxtBuildingName;
    private javax.swing.JTextField jtxtDept;
    private javax.swing.JTextField jtxtLabName;
    private javax.swing.JTextField jtxtLabNo;
    private javax.swing.JTextField jtxtNoSys;
    private javax.swing.JButton jtxtSubmit;
    // End of variables declaration//GEN-END:variables
private void systemExit()
    {
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}
