/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineSysMng;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author romi
 */
public class Not_Working extends javax.swing.JFrame {

    /**
     * Creates new form Not_Working
     */
    public Not_Working() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtSystemNo = new javax.swing.JTextField();
        jtxtAssistantId = new javax.swing.JTextField();
        jtxtLabNo = new javax.swing.JTextField();
        jtxtComponent = new javax.swing.JTextField();
        jbtnSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnbck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Assistant_Id");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 460, 180, 40);

        jLabel2.setFont(new java.awt.Font("Chiller", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOT_WORKING");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 60, 350, 60);

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("System_No.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 290, 180, 40);

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Component");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 380, 180, 40);

        jLabel5.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Lab_No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 210, 180, 40);

        jtxtSystemNo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jtxtSystemNo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtSystemNo.setText("Enter System Number here...");
        jtxtSystemNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true));
        jtxtSystemNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSystemNoMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtSystemNo);
        jtxtSystemNo.setBounds(260, 290, 330, 40);

        jtxtAssistantId.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jtxtAssistantId.setForeground(new java.awt.Color(153, 153, 153));
        jtxtAssistantId.setText("Enter Assistant_Id here...");
        jtxtAssistantId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true));
        jtxtAssistantId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtAssistantIdMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtAssistantId);
        jtxtAssistantId.setBounds(260, 460, 330, 40);

        jtxtLabNo.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jtxtLabNo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtLabNo.setText("Enter Lab Number here...");
        jtxtLabNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true));
        jtxtLabNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLabNoMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtLabNo);
        jtxtLabNo.setBounds(260, 210, 330, 40);

        jtxtComponent.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        jtxtComponent.setForeground(new java.awt.Color(153, 153, 153));
        jtxtComponent.setText("Enter Component here...");
        jtxtComponent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true));
        jtxtComponent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtComponentMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtComponent);
        jtxtComponent.setBounds(260, 380, 330, 40);

        jbtnSubmit.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnSubmit.setForeground(new java.awt.Color(102, 204, 255));
        jbtnSubmit.setText("SUBMIT");
        jbtnSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        jbtnSubmit.setContentAreaFilled(false);
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSubmit);
        jbtnSubmit.setBounds(170, 560, 150, 40);

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 2, true));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 40, 600, 680);

        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 30, 600, 680);

        jbtnbck.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnbck.setForeground(new java.awt.Color(255, 255, 255));
        jbtnbck.setText("BACK");
        jbtnbck.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jbtnbck.setContentAreaFilled(false);
        jbtnbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbckActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbck);
        jbtnbck.setBounds(1330, 730, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/ill-computer-17291-1920x1200.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1580, 1010);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1584, 910));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbckActionPerformed
        systemExit();
        this.hide();
        MainPage1 mp1=new MainPage1();
        mp1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnbckActionPerformed

    private void jtxtLabNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLabNoMouseClicked
        jtxtLabNo.setText(null);
    }//GEN-LAST:event_jtxtLabNoMouseClicked

    private void jtxtSystemNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSystemNoMouseClicked
        jtxtSystemNo.setText(null);
    }//GEN-LAST:event_jtxtSystemNoMouseClicked

    private void jtxtComponentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtComponentMouseClicked
        jtxtComponent.setText(null);
    }//GEN-LAST:event_jtxtComponentMouseClicked

    private void jtxtAssistantIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtAssistantIdMouseClicked
        jtxtAssistantId.setText(null);
    }//GEN-LAST:event_jtxtAssistantIdMouseClicked

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
        try {
                 Connection con=getConnection();
                PreparedStatement ps=con.prepareStatement("Select * from Lab_Assistant la,New_Lab1 nl WHERE la.Lab_No=? AND la.Lab_Assistant_Id=? AND nl.No_Of_Systems>?");
                ps.setString(1,jtxtLabNo.getText());
                ps.setString(2,jtxtAssistantId.getText());
                ps.setString(3,jtxtSystemNo.getText());
                ResultSet rs=ps.executeQuery();
                if(rs.next()){
                ps=con.prepareStatement("INSERT INTO Not_Working(LAB_NO,System_No,Component,Lab_Assistant_Id)"+"values(?,?,?,?)");
                ps.setString(1,jtxtLabNo.getText());
                ps.setString(2,jtxtSystemNo.getText());
                ps.setString(3,jtxtComponent.getText());
                ps.setString(4,jtxtAssistantId.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Inserted");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Lab_Assistant is not there for given lab");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
    }//GEN-LAST:event_jbtnSubmitActionPerformed

    public Connection getConnection()
    {
        
        Connection con=null;
        try { 
            con=DriverManager.getConnection("jdbc:mysql://localhost/system_mgmnt","root","");
            JOptionPane.showMessageDialog(null,"Connected");
            return con;
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Not Connected");
            return null;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Not_Working.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Not_Working.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Not_Working.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Not_Working.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Not_Working().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JButton jbtnbck;
    private javax.swing.JTextField jtxtAssistantId;
    private javax.swing.JTextField jtxtComponent;
    private javax.swing.JTextField jtxtLabNo;
    private javax.swing.JTextField jtxtSystemNo;
    // End of variables declaration//GEN-END:variables
private void systemExit()
    {
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}
