/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineSysMng;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author romi
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtphno = new javax.swing.JTextField();
        jtxtadd = new javax.swing.JTextField();
        jtxtSupplierId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtnbck = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Chiller", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUPLLIER DETAILS...");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1080, 50, 410, 80);

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(990, 270, 160, 40);

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Phone No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(990, 340, 160, 40);

        jLabel5.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(990, 420, 160, 40);

        jLabel6.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Supplier_Id");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(990, 200, 160, 40);

        jtxtName.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtName.setForeground(new java.awt.Color(153, 153, 153));
        jtxtName.setText("Enter Name here...");
        jtxtName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtxtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNameMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtName);
        jtxtName.setBounds(1180, 270, 360, 40);

        jtxtphno.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtphno.setForeground(new java.awt.Color(153, 153, 153));
        jtxtphno.setText("Enter Phone Number here...");
        jtxtphno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtxtphno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtphnoMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtphno);
        jtxtphno.setBounds(1180, 340, 360, 40);

        jtxtadd.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtadd.setForeground(new java.awt.Color(153, 153, 153));
        jtxtadd.setText("Enter Address here...");
        jtxtadd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtxtadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtaddMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtadd);
        jtxtadd.setBounds(1180, 420, 360, 40);

        jtxtSupplierId.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jtxtSupplierId.setForeground(new java.awt.Color(153, 153, 153));
        jtxtSupplierId.setText("Enter Supplier Id here...");
        jtxtSupplierId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtxtSupplierId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSupplierIdMouseClicked(evt);
            }
        });
        jPanel1.add(jtxtSupplierId);
        jtxtSupplierId.setBounds(1180, 200, 360, 40);

        jButton1.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1200, 550, 160, 50);

        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(960, 50, 600, 700);

        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(970, 40, 600, 700);

        jbtnbck.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jbtnbck.setForeground(new java.awt.Color(255, 255, 255));
        jbtnbck.setText("BACK");
        jbtnbck.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jbtnbck.setContentAreaFilled(false);
        jbtnbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbckActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbck);
        jbtnbck.setBounds(1380, 790, 170, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineSysMng/69534059-cool-high-tech-wallpapers.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-200, 0, 1790, 1020);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1592, 921));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbckActionPerformed
        systemExit();
        this.hide();
        MainPage1 mp1=new MainPage1();
        mp1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnbckActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
                 Connection con=getConnection();
                PreparedStatement ps=con.prepareStatement("INSERT INTO Supplier(Supplier_id,Name,Phone_No,Address)"+"values(?,?,?,?)");
                ps.setString(1,jtxtSupplierId.getText());
                ps.setString(2,jtxtName.getText());
                ps.setString(3,jtxtphno.getText());
                ps.setString(4,jtxtadd.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Inserted");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtSupplierIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSupplierIdMouseClicked
        jtxtSupplierId.setText(null);
    }//GEN-LAST:event_jtxtSupplierIdMouseClicked

    private void jtxtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNameMouseClicked
        jtxtName.setText(null);
    }//GEN-LAST:event_jtxtNameMouseClicked

    private void jtxtphnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtphnoMouseClicked
        jtxtphno.setText(null);
    }//GEN-LAST:event_jtxtphnoMouseClicked

    private void jtxtaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtaddMouseClicked
        jtxtadd.setText(null);
    }//GEN-LAST:event_jtxtaddMouseClicked

    /**
     * @param args the command line arguments
     */
    public Connection getConnection()
    {
        
        Connection con=null;
        try { 
            con=DriverManager.getConnection("jdbc:mysql://localhost/system_mgmnt","root","");
            JOptionPane.showMessageDialog(null,"Connected");
            return con;
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MainPage1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Not Connected");
            return null;
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnbck;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtSupplierId;
    private javax.swing.JTextField jtxtadd;
    private javax.swing.JTextField jtxtphno;
    // End of variables declaration//GEN-END:variables
private void systemExit()
    {
        WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}
